version: "3.9"
services:
  web:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:?must_be_set}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential/teama-service-account.json
      - BRAVE_API_KEY=${BRAVE_API_KEY:-dummy_key}
      - SMITHERY_API_KEY=${SMITHERY_API_KEY:-dummy_key}
      - VISIONSTORY_API_KEY=${VISIONSTORY_API_KEY:-dummy_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-default-key}
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-backend}
    volumes:
      - ./credential:/app/credential

  celery:
    build: .
    container_name: celery
    command: celery -A config worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:?must_be_set}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential/teama-service-account.json
      - BRAVE_API_KEY=${BRAVE_API_KEY:-dummy_key}
      - SMITHERY_API_KEY=${SMITHERY_API_KEY:-dummy_key}
      - VISIONSTORY_API_KEY=${VISIONSTORY_API_KEY:-dummy_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-default-key}
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-backend}
    volumes:
      - ./credential:/app/credential

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
               echo "Starting Redis with password protection...";
               redis-server --requirepass "$$REDIS_PASSWORD";
             else
               echo "WARNING: Starting Redis WITHOUT password protection!";
               echo "This is ONLY safe for development environments.";
               redis-server;
             fi'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
