version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    environment:
      - DB_TYPE=sqlite3
      - DB_NAME=db.sqlite3
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
