version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    environment:
      - DB_TYPE=mysql
      - DB_NAME=teama_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"