global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data' #프로메테우스 "job_name" 이름
    static_configs: #메트릭 수집 설정
      - targets: ['prometheus:9090'] #메트릭을 수집하려는 타겟