# Generated by Django 5.2.3 on 2025-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
        migrations.AddField(
            model_name="video",
            name="artist",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="place_id",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
