# Generated by Django 5.2.4 on 2025-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_museum_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
