# Generated by Django 5.2.3 on 2025-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_alter_video_thumbnail_url_alter_video_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
