# Generated by Django 5.2.3 on 2025-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='placeId',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnailUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='videoUrl',
            field=models.URLField(default=''),
        ),
    ]
