# Generated by Django 5.2.3 on 2025-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_file_video_artist_video_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='placeId',
            new_name='place_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnailUrl',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videoUrl',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
